name = "JuLoop"
uuid = "d55b5b02-8cda-4f93-b17c-db526b0c8f3b"
authors = ["Meredith Julian <mjulian@mit.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
